import type { Metadata } from "next";
import { Modak, Ubuntu } from "next/font/google";
import "./globals.css";

const modak = Modak({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-modak',
  display: 'swap',
});

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: "300",
  variable: '--font-ubuntu',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Receitinhas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${modak.variable} ${ubuntu.variable}` + ' bg-food-pattern bg-repeat'}>{children}</body>
    </html>
  );
}
