import type { Metadata } from "next";
import { Modak } from "next/font/google";
import "./globals.css";

const modak = Modak({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Receitinhas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={modak.className + ' bg-food-pattern bg-repeat'}>{children}</body>
    </html>
  );
}
